##########################################################################
FROM dev-cuda-runtime AS dev-cuda-toolkit
SHELL ["/bin/bash", "-c"]

### CUDA Toolkit 11.7
RUN  distribution=$(. /etc/os-release;echo $ID$VERSION_ID | sed -e 's/\.//g') && \
     wget https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/cuda-$distribution.pin -P /tmp && \
     mv /tmp/cuda-$distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
     apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/3bf863cc.pub && \
     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64 /" | tee /etc/apt/sources.list.d/cuda.list && \
     apt-get update -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT} && \
     apt-get install -y --no-install-recommends cuda-toolkit-11-7 -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT} && \
     rm -rf /var/lib/apt/lists/* && apt-get clean && rm -rf /etc/apt/sources.list.d/cuda.list 

### Build essentials
RUN apt-get update && apt-get install -y -q --no-install-recommends \
     build-essential cmake libc6-dev git libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev && \
     rm -rf /var/lib/apt/lists/* && apt-get clean
