##########################################################################
# dev-base-cpu
##########################################################################
FROM tb5zhh/dev-base:py37

### numpy torch
RUN pip3 install numpy==1.21.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install torch==1.12.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu -i https://pypi.tuna.tsinghua.edu.cn/simple