##########################################################################
FROM ubuntu:focal AS conda
SHELL ["/bin/bash", "-c"]
ARG PROXY_HOST=127.0.0.1
ARG PROXY_PORT=50000

### wget
RUN apt-get update -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT} && \
     apt-get install -y --no-install-recommends wget -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT}

### conda
WORKDIR /opt
RUN wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh -O Miniconda3.sh && \
     chmod +x Miniconda3.sh && \
     ./Miniconda3.sh -b -p /opt/conda -f
ENV PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN pip3 install --upgrade pip \
     -i https://pypi.tuna.tsinghua.edu.cn/simple

### numpy torch
RUN pip3 install numpy==1.21.1 \
     -i https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip3 install torch --extra-index-url https://download.pytorch.org/whl/cu116 \
    #  -i https://pypi.tuna.tsinghua.edu.cn/simple
ADD ./torch-1.12.0+cpu-cp37-cp37m-linux_x86_64.whl .
RUN pip3 install torch-1.12.0+cpu-cp37-cp37m-linux_x86_64.whl \
     -i https://pypi.tuna.tsinghua.edu.cn/simple

##########################################################################
FROM ubuntu:focal AS base
SHELL ["/bin/bash", "-c"]

RUN apt-get update -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT} && \
     apt-get install -y --no-install-recommends -o Acquire::http::proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     ca-certificates gnupg2 && \
     rm -rf /var/lib/apt/lists/* && \
     apt-get clean 
ADD sources.list /etc/apt/

RUN echo 'Etc/UTC' > /etc/timezone && \
     ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
     apt-get update && \
     apt-get install -y --no-install-recommends \
     tzdata dirmngr wget&& \
     rm -rf /var/lib/apt/lists/* && apt-get clean

WORKDIR /opt
COPY --from=conda /opt/conda /opt/conda
RUN /opt/conda/bin/conda init
ENV PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update && \
     apt-get install -y --no-install-recommends \
     build-essential libc-dev cmake && \
     rm -rf /var/lib/apt/lists/* && apt-get clean
### image: dev-cpu-runtime
### with conda, numpy, torch and cuda-drivers