##########################################################################
FROM tb5zhh/dev-base:py37
SHELL ["/bin/bash", "-c"]

### numpy torch
RUN pip3 install numpy==1.21.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install torch==1.12.0+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 -i https://pypi.tuna.tsinghua.edu.cn/simple

ADD proxy.sh /opt/proxy.sh
ADD direct.sh /opt/direct.sh
RUN source proxy.sh && distribution=$(. /etc/os-release;echo $ID$VERSION_ID | sed -e 's/\.//g') && \
     wget https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/cuda-$distribution.pin -P /tmp && \
     mv /tmp/cuda-$distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
     apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/3bf863cc.pub && \
     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64 /" | tee /etc/apt/sources.list.d/cuda.list && \
     apt-get update && apt-get install -y --no-install-recommends cuda-toolkit-11-7 && \
     rm -rf /var/lib/apt/lists/* && apt-get clean && rm -rf /etc/apt/sources.list.d/cuda.list && source direct.sh

### Build essentials
RUN apt-get update && apt-get install -y -q --no-install-recommends \
     build-essential cmake libc6-dev git libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev && \
     rm -rf /var/lib/apt/lists/* && apt-get clean
