version: "0.1"
services:
  rosmaster:
    image: ros:noetic-ros-core
    container_name: rosmaster
    hostname: rosmaster
    command: roscore
    tty: true 
    # stdin_open: true
    networks:
      - private
  rosnode:
    build: simulator
    image: sim
    environment:
      - ROS_MASTER_URI=http://rosmaster:11311/
    networks:
      - private
    depends_on:
      - rosmaster
    command: ["rostopic", "list"]
  

networks:
  private:
    driver: bridge