version: "0.1"
services:
  rosmaster:
    image: ros:noetic-ros-core
    container_name: rosmaster
    hostname: rosmaster
    command: roscore
    tty: true 
    # stdin_open: true
    networks:
      - private
  rosnode:
    build: simulator
    image: sim
    environment:
      - ROS_MASTER_URI=http://rosmaster:11311/
    networks:
      - private
    depends_on:
      - rosmaster
    command: ["rostopic", "list"]
  registry:
    image: registry:2
    container_name: registry
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.discover-lab.com.crt
      REGISTRY_HTTP_TLS_KEY: /certs/docker.discover-lab.com.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /data/tb5zhh/docker_registry:/var/lib/registry:rw
      - /home/tb5zhh/RoboticCloud/registry/certs:/certs:ro
      - /home/tb5zhh/RoboticCloud/registry/auth:/auth:ro
    networks:
      - private
    ports:
      - "55555:5000"

  

networks:
  private:
    driver: bridge
