FROM docker.discover-lab.com:55555/rmus-2022-fall/sim-headless:v4.0.0

COPY fetch_robot.py /opt/habitat-sim/habitat_sim/robots/fetch_robot.py

WORKDIR /opt/habitat-sim

RUN CUDACXX=/usr/local/cuda-11.7/bin/nvcc python3 setup.py install --with-cuda --bullet --headless

WORKDIR /opt/workspace/src/ros_x_habitat/

ADD ros_x_habitat/src/nodes/habitat_env_node_1_batch.py /opt/workspace/src/ros_x_habitat/src/nodes/habitat_env_node.py

ADD ros_x_habitat/configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes_hw1.yaml \
     /opt/workspace/src/ros_x_habitat/configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml

ADD ros_x_habitat/src/nodes/ik1_batch.py /opt/workspace/src/ros_x_habitat/src/nodes/ik.py

