##########################################################################
FROM dev-habitat-sim AS dev-habitat-lab
ADD habitat-lab/ /opt/habitat-lab/
WORKDIR /opt/habitat-lab/
RUN pip3 install -r requirements.txt \
     -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install protobuf==3.19.1 webdataset==0.1.40 moviepy lmdb tensorboard==2.8.0 ifcfg \
     -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install pytest-runner
RUN python3 setup.py develop --all --index-url https://pypi.tuna.tsinghua.edu.cn/simple