FROM docker.discover-lab.com:55555/rmus-2022-fall/sim-headless:v4.0.0

WORKDIR /opt/workspace/src/ros_x_habitat/

ADD ros_x_habitat/src/nodes/habitat_env_node_2.py /opt/workspace/src/ros_x_habitat/src/nodes/habitat_env_node.py

ADD ros_x_habitat/configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes_hw1.yaml \
     /opt/workspace/src/ros_x_habitat/configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml

ADD ros_x_habitat/src/nodes/ik1.py /opt/workspace/src/ros_x_habitat/src/nodes/ik.py

