##########################################################################
FROM dev-cuda-toolkit AS dev-habitat-sim
ADD habitat-sim/ /opt/habitat-sim/
WORKDIR /opt/habitat-sim/
RUN pip3 install -r requirements.txt \
     -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install \
     -i https://pypi.tuna.tsinghua.edu.cn/simple \
     numpy==1.21.6
RUN CUDACXX=/usr/local/cuda-11.7/bin/nvcc python3 setup.py install --with-cuda --bullet --headless