FROM docker.discover-lab.com:55555/rmus-2022-fall/sim-headless:v4.1.0

WORKDIR /opt/workspace/src/ros_x_habitat/

ADD ros_x_habitat/src/nodes/habitat_env_node_3.py /opt/workspace/src/ros_x_habitat/src/nodes/habitat_env_node.py

